### PR TITLE
:gift: Use modscope tool to get info about Go modules

### LINKED ISSUE #220: The `go.work` should be respected
When a project has a `go.work` file, and that file lists modules, only those modules should be considered by the scripts.

If the project doesn't contain a `go.work` file, we should only act on the project root directory.

Follows up on #85

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :gift: Use modscope tool to get info about Go modules

/kind enhancement

Fixes #220

### CODE REVIEW

**Comment by kvmware** [comment]
LGTM, but I would like to you to run the shell scripts being changed through shellcheck https://www.shellcheck.net/ or use the action `reusable-style.yaml` from actions repo

**Comment by cardil** [comment]
I run shellcheck in my IDE, already.

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
