### PR TITLE
Look at package name when checking whether the shell package can be used

### PR DESCRIPTION
**Pull request by dprotaso**
Filenames shouldn't be used since we don't require repos to be checked out on the GOPATH

I got tripped up why upgrade tests couldn't run locally

### CODE REVIEW

**Comment by dprotaso** [comment]
@chizhg I don't really understand the failed test here - it doesn't seem related to my diff

**Comment by upodroid** [comment]
yeah noticed it on both my open PRs, changing unrelated files

**Comment by chizhg** [comment]
This is super weird.. The log said `test.TestFailsWithFatal` passed - https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_hack/142/pull-knative-hack-unit-tests/1484620228854812672#1:build-log.txt%3A143

**Comment by chizhg** [comment]
I have confirmed this is due to the `prow-tests` image update. Still figuring out what went wrong.

**Review by cardil — APPROVED** [review]
/lgtm

**Pull request merged**
