### PR TITLE
Add microbenchmarks scripts

### PR DESCRIPTION
**Pull request by slinkydeveloper**
These are taken from https://github.com/knative/eventing/tree/master/test.
The goal is to add later a github action to run them, so we can easily support running microbenchmarks in all the different knative projects.

Sorry in advance for my poor shell scripting abilities.

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Comment by n3wscott** [comment]
I think the failure is your scripts should define a set of bash functions that integrators use by importing them, not direct run scripts. 

See https://github.com/knative/hack/blob/master/e2e-tests.sh as an example. Note none of the other hack scripts are something you run, only something you import.

**Comment by slinkydeveloper** [comment]
@n3wscott How should I use them in my GH actions? Should I source them and run the single functions?

**Comment by slinkydeveloper** [comment]
That should do it @n3wscott

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
