### PR TITLE
hack should have a hack folder... and changed copyright years

### PR DESCRIPTION
**Pull request by maximilien**
1. `hack/hack` suggestions and reorg since makes it easy to reuse when setting up sandbox projects
2. updated copyrights to 2020

### CODE REVIEW

**Comment by coryrc** [comment]
These files are old so their copyrights should reflect their original creation date

**Comment by coryrc** [comment]
also these scripts are intended for others to use so don't belong in under a hack directory

**Comment by maximilien** [comment]
Interesting... I looked at it as here’s a template to make your project’s `hack` creation easier and streamlined with everyone else.

**Comment by coryrc** [comment]
Hmm, we should've thought about that during name creation!
It's sole purpose is to hold the test-infra/scripts directory somewhere else

**Comment by maximilien** [comment]
NP @coryrc. I’ll close this then. Cheers

**Pull request closed without merging**
