### PR TITLE
Print java and mvn version

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

# Changes

- Print java and maven version (followup of https://github.com/knative/test-infra/pull/2753)

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
I think the `pull-knative-hack-kind-tests` failure is not related to this PR (given the other test pass)

**Review by n3wscott — APPROVED** [review]

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
