### PR TITLE
Update e2e-kind.sh

### PR DESCRIPTION
**Pull request by davidhadas**
manual renaming

### CODE REVIEW

**Review by upodroid — CHANGES_REQUESTED** [review]
Can you fix the linting errors suggested by the linter?

**Comment by kvmware** [comment]
We was instructed to do so https://cloud-native.slack.com/archives/C04LY4M2G49/p1692208028070579?thread_ts=1692207828.557749&cid=C04LY4M2G49 here before as well.

This will not be merged with failing tests
/hold
until lint tests are fixed

**Comment by kvmware** [comment]
Not meant to upset, but part of the agreement for the renaming initiative you requested was that you would have to do more than run a simple sed to rename things and help get repos working with the new rename. So, far you have not done any of that which you agreed to and now extra work is landing on us (infra) and repo owners which was something that was explicitly we didnt want to see.

**Comment by davidhadas** [comment]
> Not meant to upset, but part of the agreement for the renaming initiative you requested was that you would have to do more than run a simple sed to rename things and help get repos working with the new rename. So, far you have not done any of that which you agreed to and now extra work is landing on us (infra) and repo owners which was something that was explicitly we didnt want to see.

That is completely incorrect and represent your own attitude against this effort from day 1. 

***It was explicitly decided that the responsibility is on the owners of the repos to make the changes*** 

I did volunteer to steer this effort, however given what you wrote, until there is a clear decision on this at the TOC and clear agreement  as for repo owners taking responsibility, I am not going to volunteer any more of my time to this effort.

**Comment by upodroid** [comment]
This isn't helpful.

Krsna rightfully felt from the beginning that this was a very large and complex endeavour, but we did a good job so far so let's get this over the finish line. The changes the linter is asking for are extremely trivial and far less than we spent on writing these comments.

**Comment by davidhadas** [comment]
no loger relevant

**Pull request closed without merging**
