### PR TITLE
:bug: Find checksums file works with ARTIFACTS_TO_PUBLISH variable

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Find checksums file works with ARTIFACTS_TO_PUBLISH variable

/kind bug

Fixes https://github.com/knative/hack/issues/272
Follow up to https://github.com/knative/hack/pull/268

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
Not a blocker, but what is the kn-event release script doing that is different from the other kn-* scripts?

/hold

**Comment by cardil** [comment]
> @upodroid: Not a blocker, but what is the kn-event release script doing that is different from the other kn-* scripts?

The kn-plugin-repo is unique in a couple of places. I often use it as a proving grounds for new development approaches.

A couple of differences from the top of my head:

- it uses mostly the Go-native built tools (via [magetasks](https://github.com/wavesoftware/go-magetasks)), instead of bash scripts
- have multiple `go.mod` files and a `go.work`
- builds artifacts and a checksums file in `build` subdirectory

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
