### PR TITLE
:bug: Revert of #257

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Revert of #257

/kind bug

Related to https://github.com/knative-sandbox/kn-plugin-event/issues/242

### CODE REVIEW

**Comment by dprotaso** [comment]
Sorry - what's the context for the revert - I went to the linked issue and wasn't clear _why_ you want the cache back.

I guess to clarify was the change a NOOP or did it make it worse?

**Comment by dprotaso** [comment]
nm - saw your 3rd edit

/lgtm

**Comment by cardil** [comment]
Yes, the https://github.com/knative/test-infra/pull/3623 was a real fix for https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Pull request merged**
